### ISSUE TITLE
boost::mpl::integral_c broken in Clang trunk

### ISSUE THREAD

**Issue by jyknight** [boostorg/mpl#69] opened 2022-08-04 22:12 UTC
Clang has recently [addressed](https://reviews.llvm.org/D130058) an [issue](https://github.com/llvm/llvm-project/issues/50055) where it failed to diagnose the UB of casting an out-of-range integer to an enum in a constant expression.

Since undefined behavior is not allowed in a constant expression, Clang now prohibits `enum test { zero }; constexpr int g = static_cast<test>(-1);` with "error: constexpr variable 'g' must be initialized by a constant expression; note: integer value -1 is outside the valid range of values [0, 1] for this enumeration type"

This change breaks boost::mpl::integral_c, since it does exactly that. Demonstrated with example, below ([and on godbolt](https://godbolt.org/z/Gf3fvGvPT))
```
#include <boost/mpl/integral_c.hpp>
enum test { zero, one };
boost::mpl::integral_c<test, zero> m;
```

Originally discovered with a program that was using the boost::numeric library, which in turn uses mpl like the above example.
```
#include <boost/numeric/conversion/udt_builtin_mixture.hpp>
boost::numeric::udt_builtin_mixture<int, int> m;
```

**Comment by dabrahams** [comment] 2022-08-09 04:34
My C++ is old, rusty and outdated, but I don't believe there's actually a fix for this.  I tried using [this](https://gist.github.com/dabrahams/0f86f4fd290d337967ce419c4f4027ca) reduced example.

The fundamental problem seems to be that the expression `n - 1` has type `int` when `n` is an instance of `enum X`, and there appears to be no way to convert that `int` back into an `X` *in a constant expression*.  So when `n - 1` is in range, there’s an error at the defintion of `prior` , and when `n - 1` is out of range, the `is_valid` technique fails to rule it out, because the type of that `static_cast` is perfectly fine; it’s just the value that’s out of range.

**Comment by dabrahams** [comment] 2022-08-09 04:40
If my previous statement is right, then the workaround for Boost is to open `boost/numeric/conversion/*enum.hpp`, and add 2 cases to each `enum` defined therein.  `_error_DO_NOT_USE_DARNIT=-1`  at the beginning and `_error_DO_NOT_USE_PLEASE` at the end.

**Comment by dabrahams** [comment] 2022-08-09 04:44
Oh, and the fix for Boost.MPL is to document this limitation of `integral_c` when used with `enum`s.

**Comment by dabrahams** [comment] 2022-08-09 18:23
The fix looks like [this](https://godbolt.org/z/WY7e6o1WW).

**Comment by dabrahams** [comment] 2022-08-10 02:19
Actually I'm back to believing there's no true fix if next and prior have to be of type `integral_c<T, ...>`.

**Comment by jyknight** [comment] 2022-08-16 17:59
Perhaps the correct fix is to somehow cause the next/prior members to be omitted when they're impossible to represent, just like they're omitted for bool? I expect that's possible somehow via some template specialization magic.


Note that Clang has been changed since a week ago to no longer have this be an unconditional error. Now it's a controllable warning `-Wenum-constexpr-conversion`, which by default is enabled as an error. However, it's suppressed in system headers, and can be downgraded/disabled in user code as well.  So, to see the error in the godbolt example you'll now need to add `-Wsystem-headers` to the compiler options. (e.g. https://godbolt.org/z/v4PPjW1n1)

Since most code using boost will be using it as a system header, they'll also not see the error, and anyone else may downgrade the error to a warning or disable it entirely if desired. However, it may become an unconditional error again in some future release of Clang, so it'd still be good to address it.

**Comment by dabrahams** [comment] 2022-08-16 19:48
> Perhaps the correct fix is to somehow cause the next/prior members to be omitted when they're impossible to represent, just like they're omitted for bool? I expect that's possible somehow via some template specialization magic.

Well, that's what I investigated, and my (ill-informed) conclusion is that it's not possible.  The problem is that the the only expressions that try to create the representation (`static_cast<test>(-1)`) are not constant expressions, and they're well-typed.

**Comment by dabrahams** [comment] 2022-08-23 18:09
I don't think that's the intent, but it is a decent workaround for the problem.  I don't believe the intent is actually realizable, but like I said, I no longer really know C++, so I might be wrong.

**Comment by ecatmur** [comment] 2022-11-16 01:36
the `static const` trick works: https://godbolt.org/z/KrhdzqYbx
```c++
enum test { zero, one };
template<class E, E a>
E const k = static_cast<E>(a - 1);
template<class T, T> struct S {};
template<class> int f();
int g() { return f<S<test, k<test, zero>>>(); }
```
this means that going all the way back to the EDG implementation/workaround actually "fixes" it: https://godbolt.org/z/8bTerz3WM
```c++
#define __EDG_VERSION__ 242
#include <boost/mpl/integral_c.hpp>
enum test { zero, one };
boost::mpl::integral_c<test, zero> m;
```

**Comment by smeenai** [comment] 2023-10-16 19:59
Was there any progress here? Clang landed https://github.com/llvm/llvm-project/pull/67528 which makes this an error by default even in system headers. We can turn off the warning for now, but that option will be removed in a future Clang release, so this will need to be addressed before then.

**Comment by carlosgalvezp** [comment] 2023-11-24 14:44
Hi! Any progress? What is the ETA for fixing? Next Clang release in about 6 months will turn the warning into a non-suppressable hard error.

**Comment by kencu** [comment] 2023-12-20 19:04
we are running into this issue now on MacPorts. current boost builds are failing with the now-default compiler, clang-16.

various patches are being suggested, versions of the ones listed in this PR, but if at all possible, we'd like to go with the one that will be finally integrated into boost.

**Comment by EduPonz** [comment] 2024-02-17 08:33
We have hit the same issue (see [here](https://github.com/eProsima/Fast-DDS/actions/runs/7934205654/job/21664653765?pr=4100#step:10:1987). It seems that macports/macports-ports#21839 does not fix it for us.

**Comment by rpopescu** [comment] 2024-06-17 17:39
Does anyone know what the latest status is, for example, which is the earliest version of boost where this is fixed?

tagging @pdimov with thanks!

**Comment by pdimov** [comment] 2024-06-18 00:13
It will be fixed in the next release, 1.86.

**Closed** 2024-06-18 00:12 UTC

**Comment by rpopescu** [comment] 2024-06-21 16:28
Thank you!

**Comment by Artalus** [comment] 2024-08-21 08:04
We are currently unable to update our Boost to 1.86 - but can patch and rebuild the version we currently use, and would like to backport the needed changes locally, to build our 1.75 with newer Clang. I checked the history of this issue, and it seems that the combination of

- this change in `numeric`: https://github.com/boostorg/numeric_conversion/commit/50a1eae942effb0a9b90724323ef8f2a67e7984a

- and this change in MPL: https://github.com/boostorg/mpl/pull/77

does fix the build error for us. Since we are using Conan to provide third-party libraries, I also thought it might be a good idea to share such patch with a bigger audience.
@pdimov apologies, but could you maybe confirm if [this patch](https://github.com/conan-io/conan-center-index/pull/24967/files#diff-400b59cc4a38af4bdd393f5fdb3e6086e809abb9508b3bb017e6dd854a2d4676) is indeed sufficient for a fix, and does not miss anything not mentioned in this thread?

**Comment by pdimov** [comment] 2024-08-21 08:16
I think that these two patches are sufficient, yes.

**Comment by piersh-aetheros** [comment] 2025-01-25 21:53
can this change be backported? many distros aren't shipping recent versions of boost yet. for example, RedHat 9 has Clang 18 and boost 1.75.0.

**Comment by Egorundel** [comment] 2025-02-26 08:23
Hello, guys!

Please, help me. 

I don't understand what the problem is and how to fix it. Attached screenshots of errors.

![Image](https://github.com/user-attachments/assets/19a3e901-967a-494d-9996-3b49530327d8)
![Image](https://github.com/user-attachments/assets/28be4882-9124-4d54-8c21-e8e15f5e0595)
![Image](https://github.com/user-attachments/assets/8aefd46c-8cb3-43c7-b7ee-4bd2a5044b61)

I work in Qt Creator. It seems like I’m working with the GCC compiler, but for some reason I’m getting errors due to clang...

![Image](https://github.com/user-attachments/assets/974a734d-0b0b-41cb-847b-2abc79ae43db)

Here is my version of Boost in the screenshot below (1.74.0):

![Image](https://github.com/user-attachments/assets/ebc6d50c-eae6-4219-936e-7cdd4b1028af)

Ubuntu version: 22.04
